apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-app
  description: This is a sample React application
  annotations:
    github.com/project-slug: thakkarpurvesh-xebia/i18next-tutorial-yt
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: development
  lifecycle: experimental