site_name: 'react-app'
site_description: 'Main documentation for react-app'
repo_url: https://github.com/thakkarpurvesh-xebia/i18next-tutorial-yt
edit_uri: edit/master/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'